pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
      - check-success=Lint
      - check-success=test
      - check-success=Analyse
    actions:
      merge:
        method: merge
  - name: Automatic merge for dependabot
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - check-success=Lint
      - check-success=test
    actions:
      merge:
        method: merge