name: 'Access Groups'
description: 'https://github.com/sudojunior/test-action'
author: 'sudojunior'
inputs:
  github-token:
    required: false
    default: ${{ github.token }}
    description: >
      A GitHub Actions credentials key (either `github.token` or `secrets.GITHUB_TOKEN`) [Read More on GitHub Docs](https://docs.github.com/en/actions/reference/authentication-in-a-workflow).
      Used to access organization or sponsor details (future, but recommended for when it does get released).
outputs:
  groups:
    description: A list of groups that fit the user, in order of percieved hierarchy.
branding:
  icon: user-check
  color: blue
runs:
  using: 'node12'
  main: 'dist/index.js'
