name: 'Access Groups'
description: 'https://github.com/sudojunior/test-action'
author: 'sudojunior'
# inputs:
#   endpoint:
#     required: false
#     default: https://api.github.com
#     description: "Used on self-hosted enterprise instances."
outputs:
  groups:
    description: A list of groups that fit the user, in order of percieved hierarchy.
branding:
  icon: user-check
  color: blue
runs:
  using: 'node12'
  main: 'dist/index.js'
