# Based on Snazzah/slash-create auto lint
# https://github.com/Snazzah/slash-create/blob/master/.github/workflows/lint.yml

name: Lint & Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install
        run: yarn

      - name: XO Format
        run: yarn format

      - name: Build
        run: yarn build

      - name: Add and Commit
        uses: EndBug/add-and-commit@v4
        with:
          add: dist
          message: "chore(format & build): Actions auto-build"
        env:
          GITHUB_TOKEN: ${{ github.token }}