name: 'Test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install
        run: yarn

      - name: Test
        # Some of the test cases cannot be properly tested until they are run as an action.
        # As a result, workarounds may be found to ensure a certain value can be found before an alternative is considered.
        run: yarn test

  clean-test: # make sure the action works on a clean machine without building
    name: 'Test action'
    needs: [build]
    strategy:
      matrix:
        actor:
          - sudojunior # repo owner #7
          # - (site admin) #6
          # - (repo collaborator) #9
          # - (repo contributor) #27
          # - (campus expert) #16
          # - (bounty hunter) #17
          # - (dev program member) #18
          # - (sponsor) #19
          # - (stargazer) #25
          # - (follower) #26
        #include:
        #  - actor: (org member #8, repo admin #11, triage #14, observer #24)
        #    repo: (org repo)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Debug Context
        run: |
          echo Actor: ${{ github.actor }}
          echo Owner/Repo: ${{ github.repository }}
          echo Event: ${{ github.event_name }}
          echo Event Action: ${{ github.event.action }}
          echo Run No.: ${{ github.run_number }}
          echo Run ID: ${{ github.run_id }}
      - uses: ./
        id: access
        # with:
          # actor: ${{ matrix.actor }}
      - name: Output Debug
        run: |
          echo ${{ github.actor }}
          echo ${{ join(steps.access.outputs.groups, ', ') }}
          echo ${{ steps.access.outputs.highest-group }}

